### ISSUE TITLE
Use settled dates as transaction dates for credit cards?

### ISSUE THREAD

**Issue by wzyboy** [wzyboy/awesome-beancount#4]
One should do balance assertions regulary. For credit cards, balance assertions could be done on statement day. If we use sale dates as transaction dates, transactions occur a few days before statement day but settled after statement day will make balance assertions fail. Example:

```
2016-02-04 * "Amazon Web Services"
  date: 2016-02-02
  Liabilities:CMB:CreditCards                 -65.00 CNY 
  Expenses:Communications:Internet            +10.00 USD @@ 65.00 CNY
```

This transaction occured on 2016-02-02 but settled on 2016-02-04 due to currency exchanges. The statement date is 2016-02-03. If we use 2016-02-02 as transaction date, the balance assertion on 2016-02-03 would fail (diff 65.00 CNY).

What do you think @sycx ?

**Comment by sycx** [comment]
When I implement the transaction-linking feature. I found I need to use the sale date to match transactions.
Then I use sale date as transaction date in output without thinking this situation.

Since the output part is independent with transaction-linking, we can use settled date as transaction date in final output

**Comment by wzyboy** [comment]
Just found a Beancount plugin that may help solve the problem: [effective_date](https://github.com/redstreet/beancount_plugins_redstreet/tree/master/effective_date).

The plugin automatically split a transaction into two based on the `effecitve_date` metadata. With this plugin, one could use sale date as transaction date while no failing balance assertions.

**Comment by wzyboy** [comment]
Hmm. Tests have shown that things may not be as easy as I thought. The split-one-transaction-into-two solution cannot handle shared expenses well. I'd still stay with original metadata solution.

**Comment by sycx** [comment]
Real world transaction is complicated. I think we should not try to resolve it. At least not in this script

In this script, my goal is just combine bills from multiple sources, and filter duplicate.
Then user can review bills in one place. 

About PR: 
  Credit card transaction may be merged by the other transaction. To use settled date in output, we should modify output of other sources. Also, transactions sorting need to adjust.
I'm working on it now

**Comment by wzyboy** [comment]
Fixed in https://github.com/wzyboy/awesome-beancount/pull/6 .

**Comment by erickguan** [comment]
I am sorry I was buried in several presentations in uni. As exponential effort @wzyboy @sycx was putting into improving importers goes, can we separate the code from `awesome-*` repo? `awesome-*` seems a better place to have cool documents, projects and links.

Please take this advice easy. A ultimate collection of importers are pretty important to all of us who have ever been in China. However, we may still keep this `awesome-beanconunt` repo useful to all other people who is interested in beancount instead of a flood of Chinese importers :smile:

Anyway, it's a initial thought. What's your opinions? I am sort of following [this guide](https://github.com/sindresorhus/awesome/blob/master/awesome.md).
